#include <precompile.h>

EXTERN_C
int luaopen_toplevel(lua_State* L);

REGISTER_WXLUA_BIND(toplevel)

int luaopen_toplevel(lua_State* L)
{
    BEGIN_LUA_TABLE(wx)
        BIND_MACRO(wxSTAY_ON_TOP)
        BIND_MACRO(wxICONIZE)
        BIND_MACRO(wxMINIMIZE)
        BIND_MACRO(wxMAXIMIZE)
        BIND_MACRO(wxCLOSE_BOX)
        BIND_MACRO(wxSYSTEM_MENU)
        BIND_MACRO(wxMINIMIZE_BOX)
        BIND_MACRO(wxMAXIMIZE_BOX)
        BIND_MACRO(wxTINY_CAPTION_HORIZ)
        BIND_MACRO(wxTINY_CAPTION_VERT)
        BIND_MACRO(wxRESIZE_BORDER)
        BIND_MACRO(wxMAXIMIZE_BOX)

        BIND_MACRO(wxDEFAULT_FRAME_STYLE)

        BIND_MACRO(wxTOPLEVEL_EX_DIALOG)

        BIND_ENUM(wxFULLSCREEN_NOMENUBAR)
        BIND_ENUM(wxFULLSCREEN_NOTOOLBAR)
        BIND_ENUM(wxFULLSCREEN_NOSTATUSBAR)
        BIND_ENUM(wxFULLSCREEN_NOBORDER)
        BIND_ENUM(wxFULLSCREEN_NOCAPTION)
        BIND_ENUM(wxFULLSCREEN_ALL)

        BIND_ENUM(wxUSER_ATTENTION_INFO)
        BIND_ENUM(wxUSER_ATTENTION_ERROR)

    END_LUA_TABLE(wx)

    return 0;
}
