#include <precompile.h>

BEGIN_WXLUA_BINDFUNC(toplevel)
    BEGIN_LUA_TABLE(wx)
        BIND_MACRO(wxSTAY_ON_TOP)
        BIND_MACRO(wxICONIZE)
        BIND_MACRO(wxMINIMIZE)
        BIND_MACRO(wxMAXIMIZE)
        BIND_MACRO(wxCLOSE_BOX)
        BIND_MACRO(wxSYSTEM_MENU)
        BIND_MACRO(wxMINIMIZE_BOX)
        BIND_MACRO(wxMAXIMIZE_BOX)
        BIND_MACRO(wxTINY_CAPTION_HORIZ)
        BIND_MACRO(wxTINY_CAPTION_VERT)
        BIND_MACRO(wxRESIZE_BORDER)
        BIND_MACRO(wxMAXIMIZE_BOX)

        BIND_MACRO(wxDEFAULT_FRAME_STYLE)

        BIND_MACRO(wxTOPLEVEL_EX_DIALOG)

        BIND_ENUM(wxFULLSCREEN_NOMENUBAR)
        BIND_ENUM(wxFULLSCREEN_NOTOOLBAR)
        BIND_ENUM(wxFULLSCREEN_NOSTATUSBAR)
        BIND_ENUM(wxFULLSCREEN_NOBORDER)
        BIND_ENUM(wxFULLSCREEN_NOCAPTION)
        BIND_ENUM(wxFULLSCREEN_ALL)

        BIND_ENUM(wxUSER_ATTENTION_INFO)
        BIND_ENUM(wxUSER_ATTENTION_ERROR)

    END_LUA_TABLE(wx)

    BEGIN_BIND_MODULE(wx)

        BEGIN_BIND_CLASS_WIN(wxTopLevelWindow)
            BIND_CTOR()

            BIND_MF(wxTopLevelWindow, Maximize)
            BIND_MF(wxTopLevelWindow, Restore)
            BIND_MF(wxTopLevelWindow, Iconize)
            BIND_MF(wxTopLevelWindow, IsMaximized)
            BIND_MF(wxTopLevelWindow, IsAlwaysMaximized)
            BIND_MF(wxTopLevelWindow, IsIconized)
            BIND_MF(wxTopLevelWindow, GetIcon)
            BIND_MF(wxTopLevelWindow, GetIcons)
            BIND_MF(wxTopLevelWindow, SetIcon)
            BIND_MF(wxTopLevelWindow, SetIcons)
            BIND_MF(wxTopLevelWindow, ShowFullScreen)
            BIND_MF(wxTopLevelWindow, IsFullScreen)
            BIND_MF(wxTopLevelWindow, GetTitle)
            BIND_MF(wxTopLevelWindow, EnableCloseButton)
            BIND_MF(wxTopLevelWindow, SetShape)
            BIND_MF(wxTopLevelWindow, RequestUserAttention)
            BIND_MF(wxTopLevelWindow, IsActive)
            BIND_MF(wxTopLevelWindow, ShouldPreventAppExit)
            BIND_MF(wxTopLevelWindow, CentreOnScreen)
            BIND_MF(wxTopLevelWindow, CenterOnScreen)
            BIND_MF(wxTopLevelWindow, RemoveChild)
            BIND_MF(wxTopLevelWindow, GetDefaultItem)
            BIND_MF(wxTopLevelWindow, SetDefaultItem)
            BIND_MF(wxTopLevelWindow, GetTmpDefaultItem)
            BIND_MF(wxTopLevelWindow, SetTmpDefaultItem)
            BIND_MF(wxTopLevelWindow, Destroy)
            BIND_MF(wxTopLevelWindow, IsTopLevel)
            BIND_MF(wxTopLevelWindow, IsVisible)
            BIND_MF(wxTopLevelWindow, OnCloseWindow)
            BIND_MF(wxTopLevelWindow, OnSize)
            BIND_MF(wxTopLevelWindow, GetRectForTopLevelChildren)
            BIND_MF(wxTopLevelWindow, OnActivate)
            BIND_MF(wxTopLevelWindow, DoUpdateWindowUI)
            BIND_MF(wxTopLevelWindow, SetMinSize)
            BIND_MF(wxTopLevelWindow, SetMaxSize)
            BIND_MF(wxTopLevelWindow, DoSetSizeHints)
        END_BIND_CLASS(wxTopLevelWindow)
    END_BIND_MODULE(wx)
END_WXLUA_BINDFUNC(toplevel)
